on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install libncurses5 libncurses5-dev m4 bison gawk flex libstdc++-4.8-dev g++-multilib g++ gengetopt git gitk zlib1g-dev autoconf autopoint libtool shtool autogen mtd-utils intltool sharutils docbook-xsl-* libstdc++5 texinfo dos2unix xsltproc binutils u-boot-tools device-tree-compiler python qemu gperf liblzo2-dev uuid-dev build-essential lzma-dev liblzma-dev lzma patch cmake intltool libglib2.0-dev gtk-doc-tools libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 lib32ncurses5 libc6-dev-i386
      - name: build
        run: |
          mkdir /opt/bin
          git clone --depth=1 --single-branch https://github.com/TWShiyuLiou1997/asuswrt_k2p.git /opt/rt-n56u

          # enlarge the storage size
          # sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x80000/CONFIG_MTD_STORE_PART_SIZ=0x600000/' configs/boards/K2P/kernel-3.4.x-5.0.config
          # sed -i 's/mtd_part_size=65536/mtd_part_size=6291456/' user/scripts/mtd_storage.sh

          # Basic for me
          fakeroot ./build K2P-5.0
          mv /opt/rt-n56u/trunk/images/*.trx /opt/bin/k2p_5.0_asuswrt.trx

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: /opt/bin
